package zango.example.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import zango.example.model.Books;

import zango.example.service.BooksLocalServiceUtil;

/**
 * The extended model base implementation for the Books service. Represents a row in the &quot;helloService_Books&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BooksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BooksImpl
 * @see zango.example.model.Books
 * @generated
 */
public abstract class BooksBaseImpl extends BooksModelImpl implements Books {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a books model instance should use the {@link Books} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BooksLocalServiceUtil.addBooks(this);
        } else {
            BooksLocalServiceUtil.updateBooks(this);
        }
    }
}
